baseURL = "/"
languageCode = "en-us"
title = "Bokmark Pages"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "架构"
    url = "/arch/"
    weight = 2

[[menu.main]]
    name = "系统源码"
    url = "/framework/"
    weight = 3

[[menu.main]]
    name = "Java"
    url = "/java/"
    weight = 4

[[menu.main]]
    name = "Kotlin"
    url = "/kotlin/"
    weight = 5

[[menu.main]]
    name = "多线程"
    url = "/mulitthread/"
    weight = 6

[[menu.main]]
    name = "杂记"
    url = "/notes/"
    weight = 7

[[menu.main]]
    name = "开源框架"
    url = "/opensources/"
    weight = 8

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 9

[params]
  google_analytics_id=""
  homepage_button_link = '/docs/about'
  homepage_button_text = 'Who am I'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = '/images/terminal.gif'
  mainSections = ["arch", "framework", "java", "kotlin" ,"mulitthread", "notes","opensources", "docs"]

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
