baseURL = "https://bokmark.github.io/"
publishdir = "docs"
languageCode = "en-us"
title = "Bokmark Pages"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "架构"
    url = "/arch/"
    weight = 2

[[menu.main]]
    name = "Android"
    url = "/android/"
    weight = 3

[[menu.main]]
    name = "Java"
    url = "/java/"
    weight = 4

[[menu.main]]
    name = "Kotlin"
    url = "/kotlin/"
    weight = 5

[[menu.main]]
    name = "操作系统"
    url = "/opreation_system/"
    weight = 6

[[menu.main]]
    name = "多线程"
    url = "/mulitthread/"
    weight = 7

[[menu.main]]
    name = "杂记"
    url = "/notes/"
    weight = 8

[[menu.main]]
    name = "开源框架"
    url = "/open_sources/"
    weight = 9

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 10

[params]
  google_analytics_id=""
  homepage_button_link = '/docs/about'
  homepage_button_text = 'Who am I'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = '/starsky.JPG'
  mainSections = ["arch", "android", "java", "kotlin", "opreation_system", "mulitthread", "notes", "open_sources", "docs"]

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "MaQian, Bokmark, JayceMa, QQDDS, Lol, camera"
    meta_og_title = "bokmark pages"
    meta_og_type = "website"
    meta_twitter_card = "summary"
    meta_twitter_site = "@bokmark"
    meta_twitter_creator = "@bokmark"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
